import { Layers } from "lucide-react";
import { SiDart, SiFlutter, SiGo } from "react-icons/si";

import { ContributionItem } from "@/@types/community";

export const contributions: ContributionItem[] = [
  {
    typeKey: "items.materials.type",
    title: "Materials",
    descriptionKey: "items.materials.description",
    tagKeys: "items.materials.tags",
    stats: { stars: 8, forks: 0 },
    icon: Layers,
    color: "text-zinc-400",
    bg: "bg-zinc-900/40",
    gradient: "from-zinc-500/20 via-zinc-800/5 to-transparent",
    border: "group-hover:border-zinc-500/30",
    command: "git clone github.com/dariomatias-dev/materials",
    repoUrl: "https://github.com/dariomatias-dev/materials",
  },
  {
    typeKey: "items.scrollInfinity.type",
    title: "Scroll Infinity",
    descriptionKey: "items.scrollInfinity.description",
    tagKeys: "items.scrollInfinity.tags",
    stats: { stars: 2, forks: 0 },
    icon: SiFlutter,
    color: "text-blue-400",
    bg: "bg-blue-950/30",
    gradient: "from-blue-500/20 via-blue-900/5 to-transparent",
    border: "group-hover:border-blue-500/30",
    command: "flutter pub add scroll_infinity",
    repoUrl: "https://github.com/dariomatias-dev/scroll_infinity",
  },
  {
    typeKey: "items.syntaxHighlighter.type",
    title: "Flutter Syntax Highlighter",
    descriptionKey: "items.syntaxHighlighter.description",
    tagKeys: "items.syntaxHighlighter.tags",
    stats: { stars: 2, forks: 0 },
    icon: SiFlutter,
    color: "text-purple-400",
    bg: "bg-purple-950/30",
    gradient: "from-purple-500/20 via-purple-900/5 to-transparent",
    border: "group-hover:border-purple-500/30",
    command: "flutter pub add flutter_syntax_highlighter",
    repoUrl: "https://github.com/dariomatias-dev/flutter_syntax_highlighter",
  },
  {
    typeKey: "items.goValidators.type",
    title: "Go Validators",
    descriptionKey: "items.goValidators.description",
    tagKeys: "items.goValidators.tags",
    stats: { stars: 2, forks: 0 },
    icon: SiGo,
    color: "text-cyan-400",
    bg: "bg-cyan-950/30",
    gradient: "from-cyan-500/20 via-cyan-900/5 to-transparent",
    border: "group-hover:border-cyan-500/30",
    command: "go get github.com/dariomatias-dev/go-validators",
    repoUrl: "https://github.com/dariomatias-dev/go-validators",
  },
  {
    typeKey: "items.errorHandling.type",
    title: "Flutter Error Handling",
    descriptionKey: "items.errorHandling.description",
    tagKeys: "items.errorHandling.tags",
    stats: { stars: 1, forks: 0 },
    icon: SiDart,
    color: "text-red-400",
    bg: "bg-red-950/30",
    gradient: "from-red-500/20 via-red-900/5 to-transparent",
    border: "group-hover:border-red-500/30",
    command:
      "git clone https://github.com/dariomatias-dev/flutter_error_handling",
    repoUrl: "https://github.com/dariomatias-dev/flutter_error_handling",
  },
];
