import { FaJava } from "react-icons/fa";
import {
  SiAmazonwebservices,
  SiDart,
  SiDocker,
  SiExpress,
  SiFastify,
  SiFirebase,
  SiFlutter,
  SiGit,
  SiGo,
  SiLinux,
  SiMongodb,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPrisma,
  SiPython,
  SiReact,
  SiRedis,
  SiShadcnui,
  SiSpring,
  SiSqlite,
  SiTailwindcss,
  SiTypescript,
} from "react-icons/si";

import { TechStackItem } from "@/@types/tech-stack";

export const techStack: TechStackItem[] = [
  {
    name: "React",
    category: "Frontend",
    desc: "The library for web and native user interfaces. Build UIs from individual pieces called components.",
    url: "https://react.dev",
    docs: "https://react.dev/learn",
    tags: ["UI", "SPA", "Components"],
    icon: SiReact,
  },
  {
    name: "Next.js",
    category: "Frontend",
    desc: "The React Framework for production. Enables you to create high-quality web applications with hybrid rendering and API routes.",
    url: "https://nextjs.org",
    docs: "https://nextjs.org/docs",
    tags: ["SSR", "Fullstack", "Performance"],
    icon: SiNextdotjs,
  },
  {
    name: "TypeScript",
    category: "Frontend",
    desc: "JavaScript with syntax for types. Adds safety and powerful tools for any scale of project.",
    url: "https://www.typescriptlang.org",
    docs: "https://www.typescriptlang.org/docs/",
    tags: ["Typing", "Safety", "Scalability"],
    icon: SiTypescript,
  },
  {
    name: "Tailwind CSS",
    category: "Frontend",
    desc: "Rapidly build modern websites without leaving your HTML. A utility-first CSS framework packed with classes.",
    url: "https://tailwindcss.com",
    docs: "https://tailwindcss.com/docs",
    tags: ["CSS", "Productivity", "Design System"],
    icon: SiTailwindcss,
  },
  {
    name: "shadcn/ui",
    category: "Frontend",
    desc: "Beautifully designed components that you can copy and paste into your apps. Accessible and customizable.",
    url: "https://ui.shadcn.com",
    docs: "https://ui.shadcn.com/docs",
    tags: ["UI Kit", "Accessibility", "Radix"],
    icon: SiShadcnui,
  },
  {
    name: "Flutter",
    category: "Mobile",
    desc: "Google's UI toolkit for building natively compiled applications for mobile, web, and desktop.",
    url: "https://flutter.dev",
    docs: "https://docs.flutter.dev",
    tags: ["Cross-Platform", "Widgets", "Google"],
    icon: SiFlutter,
  },
  {
    name: "Dart",
    category: "Mobile",
    desc: "Client-optimized language for fast apps on any platform.",
    url: "https://dart.dev",
    docs: "https://dart.dev/guides",
    tags: ["Language", "Productivity", "Type Safe"],
    icon: SiDart,
  },
  {
    name: "Node.js",
    category: "Backend",
    desc: "Asynchronous event-driven JavaScript runtime designed to build scalable network applications.",
    url: "https://nodejs.org",
    docs: "https://nodejs.org/en/docs/",
    tags: ["Server", "JS Runtime", "API"],
    icon: SiNodedotjs,
  },
  {
    name: "Java",
    category: "Backend",
    desc: "Object-oriented programming language, robust and secure. Industry standard for enterprise applications.",
    url: "https://www.java.com",
    docs: "https://docs.oracle.com/en/java/",
    tags: ["OOP", "Enterprise", "Robustness"],
    icon: FaJava,
  },
  {
    name: "Spring Boot",
    category: "Backend",
    desc: "Framework that simplifies the development of Spring-based Java applications, focused on convention over configuration.",
    url: "https://spring.io/projects/spring-boot",
    docs: "https://docs.spring.io/spring-boot/docs/current/reference/html/",
    tags: ["Java", "Framework", "Microservices"],
    icon: SiSpring,
  },
  {
    name: "Express",
    category: "Backend",
    desc: "Fast, unopinionated, minimalist web framework for Node.js, providing a robust set of features.",
    url: "https://expressjs.com",
    docs: "https://expressjs.com/en/starter/installing.html",
    tags: ["Framework", "Minimalist", "Http"],
    icon: SiExpress,
  },
  {
    name: "Fastify",
    category: "Backend",
    desc: "Web framework highly focused on providing the best developer experience with the least overhead.",
    url: "https://fastify.dev",
    docs: "https://fastify.dev/docs/latest/",
    tags: ["Performance", "Schema", "Logging"],
    icon: SiFastify,
  },
  {
    name: "NestJS",
    category: "Backend",
    desc: "A progressive Node.js framework for building efficient, reliable, and scalable server-side applications.",
    url: "https://nestjs.com",
    docs: "https://docs.nestjs.com/",
    tags: ["Architecture", "Modular", "TypeScript"],
    icon: SiNestjs,
  },
  {
    name: "Go",
    category: "Backend",
    desc: "Open source language supported by Google. Simple, secure, and ideal for scalable systems.",
    url: "https://go.dev",
    docs: "https://go.dev/doc/",
    tags: ["Performance", "Concurrency", "Systems"],
    icon: SiGo,
  },
  {
    name: "Python",
    category: "Backend",
    desc: "Programming language that lets you work quickly and integrate systems more effectively.",
    url: "https://python.org",
    docs: "https://docs.python.org/3/",
    tags: ["AI", "Automation", "Data Science"],
    icon: SiPython,
  },
  {
    name: "Firebase",
    category: "Backend",
    desc: "Google's platform that helps you build, improve, and grow your app quickly.",
    url: "https://firebase.google.com",
    docs: "https://firebase.google.com/docs",
    tags: ["BaaS", "Realtime", "Auth"],
    icon: SiFirebase,
  },
  {
    name: "Prisma",
    category: "Database",
    desc: "Next-generation ORM for Node.js and TypeScript. Type-safe queries and declarative modeling.",
    url: "https://prisma.io",
    docs: "https://www.prisma.io/docs",
    tags: ["ORM", "TypeScript", "Migration"],
    icon: SiPrisma,
  },
  {
    name: "PostgreSQL",
    category: "Database",
    desc: "The world's most advanced open source relational database. Data reliability and integrity.",
    url: "https://postgresql.org",
    docs: "https://www.postgresql.org/docs/",
    tags: ["SQL", "Relational", "ACID"],
    icon: SiPostgresql,
  },
  {
    name: "SQLite",
    category: "Database",
    desc: "Small, fast, self-contained, high-reliability, SQL database engine library.",
    url: "https://sqlite.org",
    docs: "https://sqlite.org/docs.html",
    tags: ["Embedded", "SQL", "Lightweight"],
    icon: SiSqlite,
  },
  {
    name: "MongoDB",
    category: "Database",
    desc: "Developer data platform. Document-oriented database for modern applications.",
    url: "https://mongodb.com",
    docs: "https://www.mongodb.com/docs/",
    tags: ["NoSQL", "Documents", "Flexible"],
    icon: SiMongodb,
  },
  {
    name: "Redis",
    category: "Database",
    desc: "In-memory data structure store, used as a database, cache, and message broker.",
    url: "https://redis.io",
    docs: "https://redis.io/docs/",
    tags: ["Cache", "In-Memory", "Speed"],
    icon: SiRedis,
  },
  {
    name: "AWS",
    category: "DevOps",
    desc: "The world's most comprehensive and broadly adopted cloud, offering over 200 fully featured services.",
    url: "https://aws.amazon.com",
    docs: "https://docs.aws.amazon.com/",
    tags: ["Cloud", "Infrastructure", "Serverless"],
    icon: SiAmazonwebservices,
  },
  {
    name: "Docker",
    category: "DevOps",
    desc: "Platform for developing, shipping, and running applications. Separate your application from your infrastructure.",
    url: "https://docker.com",
    docs: "https://docs.docker.com/",
    tags: ["Containers", "Deploy", "Virtualization"],
    icon: SiDocker,
  },
  {
    name: "Git",
    category: "DevOps",
    desc: "Free and open source distributed version control system designed to handle everything.",
    url: "https://git-scm.com",
    docs: "https://git-scm.com/doc",
    tags: ["Versioning", "Collaboration", "Code"],
    icon: SiGit,
  },
  {
    name: "Linux",
    category: "DevOps",
    desc: "Open source operating system based on the Linux kernel. The foundation of modern server infrastructure.",
    url: "https://linux.org",
    docs: "https://docs.kernel.org/",
    tags: ["OS", "Server", "Open Source"],
    icon: SiLinux,
  },
];
