import { FaJava } from "react-icons/fa";
import {
  SiAmazonwebservices,
  SiDart,
  SiDocker,
  SiExpress,
  SiFastify,
  SiFirebase,
  SiFlutter,
  SiGit,
  SiGo,
  SiLinux,
  SiMongodb,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPrisma,
  SiPython,
  SiReact,
  SiRedis,
  SiShadcnui,
  SiSpring,
  SiSqlite,
  SiTailwindcss,
  SiTypescript,
} from "react-icons/si";

import { Technology } from "@/@types/tech-stack";
import { TechnologyId } from "@/enums/technology-id";

export const technologies: Record<TechnologyId, Technology> = {
  react: {
    name: "React",
    category: "Frontend",
    descriptionKey: "react",
    url: "https://react.dev",
    docs: "https://react.dev/learn",
    tags: ["UI", "SPA", "Components"],
    icon: SiReact,
  },
  nextjs: {
    name: "Next.js",
    category: "Frontend",
    descriptionKey: "nextjs",
    url: "https://nextjs.org",
    docs: "https://nextjs.org/docs",
    tags: ["SSR", "Fullstack", "Performance"],
    icon: SiNextdotjs,
  },
  typescript: {
    name: "TypeScript",
    category: "Frontend",
    descriptionKey: "typescript",
    url: "https://www.typescriptlang.org",
    docs: "https://www.typescriptlang.org/docs/",
    tags: ["Typing", "Safety", "Scalability"],
    icon: SiTypescript,
  },
  tailwindcss: {
    name: "Tailwind CSS",
    category: "Frontend",
    descriptionKey: "tailwindcss",
    url: "https://tailwindcss.com",
    docs: "https://tailwindcss.com/docs",
    tags: ["CSS", "Productivity", "Design System"],
    icon: SiTailwindcss,
  },
  shadcnui: {
    name: "shadcn/ui",
    category: "Frontend",
    descriptionKey: "shadcnui",
    url: "https://ui.shadcn.com",
    docs: "https://ui.shadcn.com/docs",
    tags: ["UI Kit", "Accessibility", "Radix"],
    icon: SiShadcnui,
  },
  flutter: {
    name: "Flutter",
    category: "Mobile",
    descriptionKey: "flutter",
    url: "https://flutter.dev",
    docs: "https://docs.flutter.dev",
    tags: ["Cross-Platform", "Widgets", "Google"],
    icon: SiFlutter,
  },
  dart: {
    name: "Dart",
    category: "Mobile",
    descriptionKey: "dart",
    url: "https://dart.dev",
    docs: "https://dart.dev/guides",
    tags: ["Language", "Productivity", "Type Safe"],
    icon: SiDart,
  },
  nodejs: {
    name: "Node.js",
    category: "Backend",
    descriptionKey: "nodejs",
    url: "https://nodejs.org",
    docs: "https://nodejs.org/en/docs/",
    tags: ["Server", "JS Runtime", "API"],
    icon: SiNodedotjs,
  },
  java: {
    name: "Java",
    category: "Backend",
    descriptionKey: "java",
    url: "https://www.java.com",
    docs: "https://docs.oracle.com/en/java/",
    tags: ["OOP", "Enterprise", "Robustness"],
    icon: FaJava,
  },
  springboot: {
    name: "Spring Boot",
    category: "Backend",
    descriptionKey: "springboot",
    url: "https://spring.io/projects/spring-boot",
    docs: "https://docs.spring.io/spring-boot/docs/current/reference/html/",
    tags: ["Java", "Framework", "Microservices"],
    icon: SiSpring,
  },
  express: {
    name: "Express",
    category: "Backend",
    descriptionKey: "express",
    url: "https://expressjs.com",
    docs: "https://expressjs.com/en/starter/installing.html",
    tags: ["Framework", "Minimalist", "Http"],
    icon: SiExpress,
  },
  fastify: {
    name: "Fastify",
    category: "Backend",
    descriptionKey: "fastify",
    url: "https://fastify.dev",
    docs: "https://fastify.dev/docs/latest/",
    tags: ["Performance", "Schema", "Logging"],
    icon: SiFastify,
  },
  nestjs: {
    name: "NestJS",
    category: "Backend",
    descriptionKey: "nestjs",
    url: "https://nestjs.com",
    docs: "https://docs.nestjs.com/",
    tags: ["Architecture", "Modular", "TypeScript"],
    icon: SiNestjs,
  },
  go: {
    name: "Go",
    category: "Backend",
    descriptionKey: "go",
    url: "https://go.dev",
    docs: "https://go.dev/doc/",
    tags: ["Performance", "Concurrency", "Systems"],
    icon: SiGo,
  },
  python: {
    name: "Python",
    category: "Backend",
    descriptionKey: "python",
    url: "https://python.org",
    docs: "https://docs.python.org/3/",
    tags: ["AI", "Automation", "Data Science"],
    icon: SiPython,
  },
  firebase: {
    name: "Firebase",
    category: "Backend",
    descriptionKey: "firebase",
    url: "https://firebase.google.com",
    docs: "https://firebase.google.com/docs",
    tags: ["BaaS", "Realtime", "Auth"],
    icon: SiFirebase,
  },
  prisma: {
    name: "Prisma",
    category: "Database",
    descriptionKey: "prisma",
    url: "https://prisma.io",
    docs: "https://www.prisma.io/docs",
    tags: ["ORM", "TypeScript", "Migration"],
    icon: SiPrisma,
  },
  postgresql: {
    name: "PostgreSQL",
    category: "Database",
    descriptionKey: "postgresql",
    url: "https://postgresql.org",
    docs: "https://www.postgresql.org/docs/",
    tags: ["SQL", "Relational", "ACID"],
    icon: SiPostgresql,
  },
  sqlite: {
    name: "SQLite",
    category: "Database",
    descriptionKey: "sqlite",
    url: "https://sqlite.org",
    docs: "https://sqlite.org/docs.html",
    tags: ["Embedded", "SQL", "Lightweight"],
    icon: SiSqlite,
  },
  mongodb: {
    name: "MongoDB",
    category: "Database",
    descriptionKey: "mongodb",
    url: "https://mongodb.com",
    docs: "https://www.mongodb.com/docs/",
    tags: ["NoSQL", "Documents", "Flexible"],
    icon: SiMongodb,
  },
  redis: {
    name: "Redis",
    category: "Database",
    descriptionKey: "redis",
    url: "https://redis.io",
    docs: "https://redis.io/docs/",
    tags: ["Cache", "In-Memory", "Speed"],
    icon: SiRedis,
  },
  aws: {
    name: "AWS",
    category: "DevOps",
    descriptionKey: "aws",
    url: "https://aws.amazon.com",
    docs: "https://docs.aws.amazon.com/",
    tags: ["Cloud", "Infrastructure", "Serverless"],
    icon: SiAmazonwebservices,
  },
  docker: {
    name: "Docker",
    category: "DevOps",
    descriptionKey: "docker",
    url: "https://docker.com",
    docs: "https://docs.docker.com/",
    tags: ["Containers", "Deploy", "Virtualization"],
    icon: SiDocker,
  },
  git: {
    name: "Git",
    category: "DevOps",
    descriptionKey: "git",
    url: "https://git-scm.com",
    docs: "https://git-scm.com/doc",
    tags: ["Versioning", "Collaboration", "Code"],
    icon: SiGit,
  },
  linux: {
    name: "Linux",
    category: "DevOps",
    descriptionKey: "linux",
    url: "https://linux.org",
    docs: "https://docs.kernel.org/",
    tags: ["OS", "Server", "Open Source"],
    icon: SiLinux,
  },
};
